# Generated by Django 4.2.5 on 2023-09-22 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_activity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storestatus',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], default='inactive', max_length=10),
        ),
    ]
